name: trailora-prod
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: armita1988/trailora-backend:v1.0.0
    container_name: trailora-prod-api
    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7000/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      start_interval: 5s
    environment:
      - NODE_ENV=production

    env_file:
      - ./config.prod.env

    ports:
      - '127.0.0.1:3000:7000'
    volumes:
      - ./uploads/users:/app/public/img/users
