FROM node:lts-bookworm-slim
WORKDIR /app
RUN apt-get update \
&& apt-get install -y --no-install-recommends curl \
&& rm -rf /var/lib/apt/lists/*
ENV NODE_ENV=production
COPY package*.json ./ 
RUN npm ci --omit=dev
COPY . . 
EXPOSE 7000
CMD ["node", "server.js" ]
